### PR TITLE
Initial attempt at task representation

### PR DESCRIPTION
**Pull request by markwhiting**
Here's an initial attempt at how we could represent tasks. We can make adjustments to this as we try it out, and I can build it into a web form once we decide we like it.

### CODE REVIEW

**Comment by markwhiting** [comment]
If you're new to Github, click on the 'files changed' tab to see the latest proposed version. You can click on any line to add comments or propose changes. After reading through the document add your review at the top right, where you will have options to request changes, comment or accept the proposal. 

The the 'commits' tab has a number grater than 1 after it, you can use that to look at how things changed over versions in this pull request.

**Comment by amaatouq** [comment]
Can you perhaps show me how would the Room Assigment task look like in this structure: https://docs.google.com/document/d/1twB6GjFI28FOV14SPFbbrp8IfYraNHn19y2c6PTsoAA/edit?usp=sharing ?

**Comment by markwhiting** [comment]
@amaatouq sure — setting that up and we can talk about it tomorrow in the meeting.

**Review by linneagandhi — CHANGES_REQUESTED** [review]
Hi @markwhiting! Possibly missing from this are (1) what the payoffs are for meeting the criteria (could include in criteria section) and (2) maybe a new section ##roles (if relevant) for group-only tasks where there are predefined roles for different individuals to take. (Sorry if I put this comment in the wrong place - I'm new to github!)

**Comment by markwhiting** [comment]
@linneagandhi let me know if you think the changes add those concepts in.

**Comment by markwhiting** [comment]
> Can you perhaps show me how would the Room Assigment task look like in this structure: https://docs.google.com/document/d/1twB6GjFI28FOV14SPFbbrp8IfYraNHn19y2c6PTsoAA/edit?usp=sharing ?

@amaatouq — I've made a [new file with sample instructions](https://docs.google.com/document/d/1yxQfHobL3vAamNgnt14korvORaI-N1ed62gHsEovHXI/edit#heading=h.byccy5gosjoj) based on the one you shared.

**Comment by JamesPHoughton** [comment]
If we end up publishing these in a "Greatest Hits of Team Research (1900-2020)" anthology, as I sincerely hope, it would be good to ensure that the answer to each question is traceable. (Will also be useful for when we document our implementations.)

- If we have to go to additional sources to get the reference implementation, whether published or online or from the author, we should have a way to capture those sources (references if they are published, otherwise screenshots or transcripts. If there is code available, we should capture a version of it.)
- If we have to make decisions or "interpret" what is written, we should justify the interpretation

At some point, we should also justify why these tasks were selected for the anthology, and why we chose those specific papers as the references.

**Comment by markwhiting** [comment]
Closes #1

**Pull request merged**
