### PR TITLE
Create Judgment of product and slogan.md

### PR DESCRIPTION
**Pull request by sarikasu**

### CODE REVIEW

**Review by sarikasu — COMMENTED** [review]
updated instructions

**Review by DodgeHill — DISMISSED** [review]
Looks good, maybe clear out the descriptions for the Stimuli section

**Review by sarikasu — COMMENTED** [review]
Updated stimuli section

**Review by sarikasu — COMMENTED** [review]
cleaned up file

**Review by DodgeHill — APPROVED** [review]
This looks good to me

**Pull request merged**
