### PR TITLE
Create Strike Group Defender (developed by Metateq, Inc.)

### PR DESCRIPTION
**Pull request by sarikasu**

### CODE REVIEW

**Review by sarikasu — COMMENTED** [review]
Added Instructions provided by researchers

**Comment by sarikasu** [comment]
@markwhiting how would you like to save/store all the detailed information from the researchers, they shared a google drive with me. Where should I put all those files.

**Comment by markwhiting** [comment]
They didn't give me access so I'm not sure what that looks like, however I'd aim for getting the instructions here reasonably good, and keep copies of those other resources in a folder in our google drive, e.g., in a folder in here https://drive.google.com/drive/u/0/folders/18vgiD6lfVLP1-cIEEXmN6DWCankqXJz1

**Comment by sarikasu** [comment]
I added the instructions here already, it just references the software and tutorial video which are in the files they provided. Uploaded to our google drive!

**Comment by markwhiting** [comment]
Great. Thanks!

**Review by KaranSampath — APPROVED** [review]

**Pull request merged**
