### PR TITLE
Apache helicopter flight simulator

### PR DESCRIPTION
**Pull request by KaranSampath**
Just creating the pull request to allow for easier tracking

### CODE REVIEW

**Review by KaranSampath — COMMENTED** [review]
@bvikram03 I think we're only supposed to focus on Experiment 1 (1 task) per issue. We could probably create a second issue for the second task

**Comment by markwhiting** [comment]
I'd say we should do the task listed in the sheet, and if there are more versions due to multiple experiments that used the same task, then we can talk about that in `Materials for alternative versions of the experiment`, but if there are distinct tasks in different experiments in a paper, we only need the focal one listed in the table for now.

**Comment by andrewcullen1** [comment]
Looks like this task needs instructions, after checking all the versions available online and OSF, I emailed one of the authors

**Comment by bvikram03** [comment]
Thanks!
ᐧ

**Comment by KaranSampath** [comment]
Added instructions and cleaned up the rest of the file.

**Review by bvikram03 — APPROVED** [review]

**Pull request merged**
