### PR TITLE
Create Iterated Snowdrift Game (aka Hawk-Dove game)

### PR DESCRIPTION
**Pull request by sarikasu**

### CODE REVIEW

**Review by katelynbottcher — APPROVED** [review]

**Comment by katelynbottcher** [comment]
When I click "view file" it still looks like the raw version. I'm wondering if that's because it wasn't named task.md?

**Comment by sarikasu** [comment]
I just renamed it and created a new pull request, does that version look better?

**Comment by markwhiting** [comment]
(btw, you shouldn't need to make a new pull request in this kind of situation, just making the change in the fork should reflect that here too)

**Comment by sarikasu** [comment]
ok, that is helpful to know!! Thank you!

**Comment by katelynbottcher** [comment]
The new pull request is asking if I want to squash and merge after I reviewed it, instead of automatically merging as usual. I'm not sure if I should do that, or if you wanted to make a change in the fork of the original and close the new pull request.

**Pull request merged**
